from Cython.Build import cythonize

rule all: 
    input:
        "results/__cythonized__",
        "results/synthetic/er/samples=10_nodes=10_p=0.5_r=0.5/pyr_1.csv",
        #"results/synthetic/er/10_0.5_0.5/cx_1.csv"

rule cythonize:
    # Cythonizes the required files.
    input:
        "src/py_raccoon/balance_sampling.pyx",
        "src/py_raccoon/balance_spanning_trees.pyx"
    output:
        # actual output filename sytem-dependent and not relevant -> __cythonized__ used to mark dependencies and detect changes by snakemake.
        "results/__cythonized__"
    shell:
        # remove option '-a' if you don't need to debug / profile
        "C_INCLUDE_PATH=$(python -c 'import numpy; print(numpy.get_include())') cythonize -i -a {input} && touch {output}"

rule exp:
    input:
        "results/__cythonized__"
    output:
        "results/synthetic/{kind}/samples={n_samples}_nodes={n_nodes}_p={prob_p}_r={prob_r}/{alg}_{run}.csv"
    script:
        "scripts/experiment.py"