from Cython.Build import cythonize

rule all: 
    input:
        "results/__cythonized__",
        "results/my_first_output.csv"

rule cythonize:
    # Cythonizes the required files.
    input:
        "src/py_raccoon/balance_sampling.pyx",
        "src/py_raccoon/balance_spanning_trees.pyx"
    output:
        # actual output filename sytem-dependent and not relevant -> __cythonized__ used to mark dependencies and detect changes by snakemake.
        "results/__cythonized__"
    shell:
        # remove option '-a' if you don't need to debug / profile
        "C_INCLUDE_PATH=$(python -c 'import numpy; print(numpy.get_include())') cythonize -i -a {input} && touch {output}"

rule first_experiment:
    output:
        "results/my_first_output.csv"
    script:
        "scripts/random_graph_csv.py"