sbm-exps:
    0:
        sizes: [10, 10]
        p: [[0.5, 0.2], [0.2, 0.5]]
        r: [[0.5, 0.5], [0.5, 0.5]]
    1:
        sizes: [10, 20]
        p: [[0.4, 0.3], [0.3, 0.4]]
        r: [[0.4, 0.3], [0.3, 0.4]]
    2:
        sizes: [5, 5]
        p: [[1, 0.1], [0.1, 1]]
        r: [[0.5, 0.0], [0.1, 0.5]]